
// Library includes

// Project includes
#include "GLWrapper.h"


/*
// Our function pointers for the ARB multitexturing functions
PFNGLMULTITEXCOORD2FARBPROC		glMultiTexCoord2fARB = NULL;
PFNGLACTIVETEXTUREARBPROC		glActiveTextureARB = NULL;

// This is our fog extension function pointer to set a vertice's depth
PFNGLFOGCOORDFEXTPROC			glFogCoordfEXT = NULL;

// This defines our point sprite extension
PFNGLPOINTPARAMETERFARBPROC		glPointParameterfARB = NULL;
PFNGLPOINTPARAMETERFVARBPROC	glPointParameterfvARB = NULL;

// GL_ARB_occlusion_query - Begin
PFNGLGENQUERIESARBPROC			glGenQueriesARB = NULL;
PFNGLDELETEQUERIESARBPROC		glDeleteQueriesARB = NULL;
PFNGLISQUERYARBPROC				glIsQueryARB = NULL;
PFNGLBEGINQUERYARBPROC			glBeginQueryARB = NULL;
PFNGLENDQUERYARBPROC			glEndQueryARB = NULL;
PFNGLGETQUERYIVARBPROC			glGetQueryivARB = NULL;
PFNGLGETQUERYOBJECTIVARBPROC	glGetQueryObjectivARB = NULL;
PFNGLGETQUERYOBJECTUIVARBPROC	glGetQueryObjectuivARB = NULL;
// GL_ARB_occlusion_query - End
*/

PFNWGLEXTSWAPCONTROLPROC		glSwapIntervalEXT = NULL;
PFNWGLEXTGETSWAPINTERVALPROC	glGetSwapIntervalEXT = NULL;


/*
// The function pointers for shaders
PFNGLCREATESHADEROBJECTARBPROC glCreateShaderObjectARB = NULL;
PFNGLSHADERSOURCEARBPROC glShaderSourceARB = NULL;
PFNGLCOMPILESHADERARBPROC glCompileShaderARB = NULL;
PFNGLCREATEPROGRAMOBJECTARBPROC glCreateProgramObjectARB = NULL;
PFNGLATTACHOBJECTARBPROC glAttachObjectARB = NULL;
PFNGLLINKPROGRAMARBPROC glLinkProgramARB = NULL;
PFNGLUSEPROGRAMOBJECTARBPROC glUseProgramObjectARB = NULL;
PFNGLUNIFORM1IARBPROC glUniform1iARB = NULL;
PFNGLUNIFORM2IARBPROC glUniform2iARB = NULL;
PFNGLUNIFORM3IARBPROC glUniform3iARB = NULL;
PFNGLUNIFORM4IARBPROC glUniform4iARB = NULL;
PFNGLUNIFORM1FARBPROC glUniform1fARB = NULL;
PFNGLUNIFORM2FARBPROC glUniform2fARB = NULL;
PFNGLUNIFORM3FARBPROC glUniform3fARB = NULL;
PFNGLUNIFORM4FARBPROC glUniform4fARB = NULL;
PFNGLUNIFORM1FVARBPROC glUniform1fvARB = NULL;
PFNGLUNIFORM2FVARBPROC glUniform2fvARB = NULL;
PFNGLUNIFORM3FVARBPROC glUniform3fvARB = NULL;
PFNGLUNIFORM4FVARBPROC glUniform4fvARB = NULL;
PFNGLUNIFORMMATRIX3FVARBPROC glUniformMatrix3fvARB = NULL;
PFNGLUNIFORMMATRIX4FVARBPROC glUniformMatrix4fvARB = NULL;
PFNGLGETUNIFORMLOCATIONARBPROC glGetUniformLocationARB = NULL;
PFNGLDETACHOBJECTARBPROC glDetachObjectARB = NULL;
PFNGLDELETEOBJECTARBPROC glDeleteObjectARB = NULL;
PFNGLPROGRAMLOCALPARAMETER4FARBPROC glProgramLocalParameter4fARB;
PFNGLBINDPROGRAMARBPROC glBindProgramARB;
PFNGLGETOBJECTPARAMETERIVARBPROC glGetObjectParameterivARB;
PFNGLGETINFOLOGARBPROC glGetInfoLogARB;
*/




void CGLDriverStates::setCullMode(CGLDriverStates::CullMode_t cullMode)
{
	glCullFace(cullMode == CCW ? GL_BACK : GL_FRONT);
	mCullMode = cullMode;
}

CGLDriverStates::CullMode_t CGLDriverStates::getCullMode() const
{
	return mCullMode;
}
